### PR TITLE
Updated build.py, removed breaking changes from manifest

### PR DESCRIPTION
**Pull request by brianjd**
* Updated build.py to be current with current template
* Removed colons from description urls (ie. https://), as this was breaking the build script

### CODE REVIEW

**Comment by markvandertol** [comment]
Thank you for sending in this request. I shall review and test these changes soon.

**Comment by markvandertol** [comment]
I was looking at your commit and I was wondering where you found the build.py you included? It differs from the version found at https://github.com/appcelerator/titanium_mobile/blob/master/iphone/templates/module/default/template/iphone/build.py.ejs

**Comment by brianjd** [comment]
It was a bad merge (poor) of a copy generated from another recent project.  I've now based it purely on the one your referenced.

**Comment by markvandertol** [comment]
We've updated the build script, thanks for pointing that out.

We had to make some changes to the manifest ourselves, so we also removed the colons. It is fixed in the latest commit. Thanks.

**Pull request closed without merging**
